---
version: '3.9'
services: 
  students-srv:
    build:
      context: .
    networks:
      - students-net
    ports:
      - target: 8080
        published: 8084
        protocol: tcp
        mode: host
    environment:
      - MYSQL_SERVER=students-db
    depends_on:
      - students-db
  students-db:
    image: mysql:5.6
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
networks:
  students-net:
    driver: bridge
    ipam:
      config:
        - subnet: '192.168.100.0/24'
